# Merge syntax not supported yet. Can't use anchors:
# https://github.com/tomzo/gocd-yaml-config-plugin/issues/63
format_version: 10
common:
  pipeline_template: &pipeline_template
    group: KiLib-OSS
    template: software-cmake-build
    label_template: ${COUNT}-${git[:7]}
    lock_behavior: none
    display_order: -1
    materials: 
      git:
        git: https://git.nibious.com/CoSci-LLC/KiLib-OSS.git
        username: gocd
        shallow_clone: false
        auto_update: true
        branch: CMakeWork
        password: "{{SECRET:[gitea-creds][password]}}"
pipelines:
  ubuntu-22.04-build-debug: 
    <<: *pipeline_template
    parameters:
      ea-profile: ubuntu-22.04
      build-type: "Debug"
      project: "kilib-oss"

  centos-9-build-debug: 
    <<: *pipeline_template
    parameters:
      ea-profile: centos-9
      build-type: "Debug"
      project: "kilib-oss"

  ubuntu-20.04-build-debug: 
    <<: *pipeline_template
    parameters:
      ea-profile: ubuntu-20.04
      build-type: "Debug"
      project: "kilib-oss"

  centos-8-build-debug: 
    <<: *pipeline_template
    parameters:
      ea-profile: centos-8
      build-type: "Debug"
      project: "kilib-oss"


#################################
### CLANG BUILDS
#################################
  ubuntu-22.04-build-clang-debug:
    <<: *pipeline_template
    parameters:
      ea-profile: ubuntu-22.04
      build-type: "Debug-clang"
      project: "kilib-oss"

  centos-9-build-clang-debug: 
    <<: *pipeline_template
    parameters:
      ea-profile: centos-9
      build-type: "Debug-clang"
      project: "kilib-oss"

  ubuntu-20.04-build-clang-debug: 
    <<: *pipeline_template
    parameters:
      ea-profile: ubuntu-20.04
      build-type: "Debug-clang"
      project: "kilib-oss"

  centos-8-build-clang-debug: 
    <<: *pipeline_template
    parameters:
      ea-profile: centos-8
      build-type: "Debug-clang"
      project: "kilib-oss"